dependencies:
  # we're using 4.0.0 since we don't need proxy beacon logic from 4.1.0
  - OpenZeppelin/openzeppelin-contracts@4.0.0

networks:
  default: mainnet-fork

autofetch_sources: true

hypothesis:
  max_examples: 10
