development:
  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      evm_version: london
      fork: mainnet
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: mainnet-fork
    name: Ganache-CLI (Mainnet Fork)
    timeout: 120
  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 5
      fork: goerli
      evm_version: london
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: goerli-fork
    name: goerli-fork
    timeout: 120
  - cmd: ./ganache.sh
    cmd_settings:
      evm_version: london
      accounts: 10
      chain_id: 5
      fork: http://127.0.0.1:7777
      gas_limit: 12000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: local-fork
    name: local-fork
    timeout: 120
