live:
  - name: Ethereum
    networks:
      - chainid: 17000
        explorer: https://api-holesky.etherscan.io/api
        host: https://holesky.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        id: holesky
        # multicall2 is missing on Holesky. New backward-compatible multicall contract.
        # See https://github.com/mds1/multicall
        multicall2: "0xcA11bde05977b3631167028862bE2a173976CA11"
        name: Holesky (Infura)
        provider: infura
development:

  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      fork: mainnet
      gas_limit: 30000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: mainnet-fork
    name: Ganache-CLI (Mainnet Fork)
    timeout: 360
    # https://github.com/mds1/multicall#multicall2-contract-addresses
    multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"

  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 5
      fork: goerli
      gas_limit: 30000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: goerli-fork
    name: Ganache-CLI (Goerli Fork)
    timeout: 360

  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 17000
      fork: holesky
      gas_limit: 30000000
      mnemonic: brownie
      port: 8545
      evm_version: shanghai
    host: http://127.0.0.1
    id: holesky-fork
    name: Ganache-CLI (Holesky Fork)
    timeout: 360

  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 11155111
      fork: sepolia
      gas_limit: 30000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: sepolia-fork
    name: Ganache-CLI (Sepolia Fork)
    timeout: 360

  - cmd: ./ganache.sh
    cmd_settings:
      accounts: 10
      chain_id: 1337
      fork: http://127.0.0.1:7777
      gas_limit: 30000000
      mnemonic: brownie
      port: 8545
    host: http://127.0.0.1
    id: local-fork
    name: Ganache-CLI (Local Fork)
    explorer: https://api.etherscan.io/api
    timeout: 360
    # https://github.com/mds1/multicall#multicall2-contract-addresses
    multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"



development:
  - name: Anvil
    id: anvil
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
  - name: Anvil (Mainnet Fork)
    id: anvil-fork
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      fork: mainnet
      port: 8545
  - name: Anvil (Holesky Fork)
    id: anvil-holesky-fork
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      fork: holesky
      port: 8545
  - name: Ganache-CLI
    id: development
    cmd: ganache-cli
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
  - name: Geth Dev
    id: geth-dev
    cmd: ethnode
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
  - name: Hardhat
    id: hardhat
    cmd: npx hardhat node
    host: http://localhost
    cmd_settings:
      port: 8545
  - name: Hardhat (Mainnet Fork)
    id: hardhat-fork
    cmd: npx hardhat node
    host: http://localhost
    timeout: 120
    cmd_settings:
      port: 8545
      fork: mainnet
  - name: Ganache-CLI (Mainnet Fork)
    id: mainnet-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: mainnet
  - name: Ganache-CLI (BSC-Mainnet Fork)
    id: bsc-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: bsc-main
  - name: Ganache-CLI (FTM-Mainnet Fork)
    id: ftm-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: ftm-main
  - name: Ganache-CLI (Polygon-Mainnet Fork)
    id: polygon-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: polygon-main
  - name: Ganache-CLI (Avax-Mainnet Fork)
    id: avax-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: avax-main
  - name: Ganache-CLI (Aurora-Mainnet Fork)
    id: aurora-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: aurora-main
  - name: Ganache-CLI (Gnosis-Mainnet Fork)
    id: gnosis-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: gnosis-main
  - name: Ganache-CLI (zkEVM-Mainnet Fork)
    id: zkevm-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: zkevm-main
  - name: Ganache-CLI Base-Mainnet Fork)
    id: base-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: base-main
