[tool.poetry]
name = "scripts"
version = "0.1.0"
description = "Repository for internal voting scripts."
authors = ["Lido devteam"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
eth-brownie = ">=1.18.1"
avotes-parser-core = { path = "../AVotesParser/production/avotes-parser-core" } # upgrade later

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
