name: Large vote CI

on:
  push:
    branches:
      - 'large-vote_**'

jobs:
  run-tests-large:
    runs-on: "ubuntu-latest"
    name: Brownie fork LARGE tests
    uses: ./.github/actions/brownie_fork_tests.yaml
    with:
      vote: "large"
