name: Large vote CI

on:
  push:
    branches:
      - "large-vote_**"

jobs:
  run-tests-large:
    name: Brownie fork LARGE tests
    runs-on: "protocol-heavy-runners"
    steps:
      - uses: actions/checkout@v3
      - name: Main action
        uses: ./.github/actions/brownie_fork_tests
        with:
          vote: "large"
          infura: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          etherscan: ${{ secrets.ETHERSCAN_TOKEN }}
