name: Weekly run all tests
on:
  schedule:
    - cron: "0 0 * * SAT"
jobs:
  run-tests-weekly:
    name: Brownie fork tests - Weekly run
    runs-on: [protocol-heavy-runners]
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - name: Main action
        uses: ./.github/actions/brownie_fork_tests
        with:
          vote: "large"
          infura: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          etherscan: ${{ secrets.ETHERSCAN_TOKEN }}
