name: Normal vote CI

on:
  push:
    branches:
      - '!large-vote_**'

jobs:
  run-tests-normal:
    name: Brownie fork NORMAL tests
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Main action
        uses: ./.github/actions/brownie_fork_tests
        with:
          vote: "normal"
