name: Normal vote CI

on:
  push:
    branches:
      - '!large-vote_**'
  workflow_dispatch:

jobs:
  run-tests-normal:
    name: Brownie fork NORMAL tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Main action
        uses: ./.github/actions/brownie_fork_tests
        with:
          vote: "normal"
